# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/registry.json
packages:
  - type: github_release
    repo_owner: grafana
    repo_name: grafanactl
    description: The Grafana CLI. Command-line tool designed to simplify interaction with Grafana resources
    version_constraint: "false"
    version_overrides:
      - version_constraint: "true"
        type: http
        url: https://gh-proxy.org/github.com/grafana/grafanactl/releases/download/{{.Version}}/grafanactl_{{.OS}}_{{.Arch}}.{{.Format}}
        asset: grafanactl_{{.OS}}_{{.Arch}}.{{.Format}}
        format: tar.gz
        replacements:
          amd64: x86_64
          darwin: Darwin
          linux: Linux
          windows: Windows
        checksum:
          type: http
          url: https://gh-proxy.org/github.com/grafana/grafanactl/releases/download/{{.Version}}/grafanactl_checksums.txt
          asset: grafanactl_checksums.txt
          algorithm: sha256
        overrides:
          - goos: windows
            type: http
            url: https://gh-proxy.org/github.com/grafana/grafanactl/releases/download/{{.Version}}/grafanactl_{{.OS}}_{{.Arch}}.{{.Format}}
            format: zip
