# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/registry.json
packages:
  - type: github_release
    repo_owner: grafana
    repo_name: alloy
    description: OpenTelemetry Collector distribution with programmable pipelines
    version_constraint: "false"
    version_overrides:
      - version_constraint: "true"
        type: http
        url: https://gh-proxy.org/github.com/grafana/alloy/releases/download/{{.Version}}/alloy-{{.OS}}-{{.Arch}}.{{.Format}}
        asset: alloy-{{.OS}}-{{.Arch}}.{{.Format}}
        format: zip
        windows_arm_emulation: true
        files:
          - name: alloy
            src: "{{.AssetWithoutExt}}"
        checksum:
          type: http
          url: https://gh-proxy.org/github.com/grafana/alloy/releases/download/{{.Version}}/SHA256SUMS
          asset: SHA256SUMS
          algorithm: sha256
        overrides:
          - goos: windows
            type: http
            url: https://gh-proxy.org/github.com/grafana/alloy/releases/download/{{.Version}}/alloy-{{.OS}}-{{.Arch}}.exe.{{.Format}}
            asset: alloy-{{.OS}}-{{.Arch}}.exe.{{.Format}}
