packages:
  - type: http
    url: https://gh-proxy.org/github.com/grafana/mcp-grafana/releases/download/{{.Version}}/mcp-grafana_{{.OS}}_{{.Arch}}.{{.Format}}
    repo_owner: grafana
    repo_name: mcp-grafana
    description: MCP server for Grafana
    asset: mcp-grafana_{{.OS}}_{{.Arch}}.{{.Format}}
    format: tar.gz
    replacements:
      amd64: x86_64
      darwin: Darwin
      linux: Linux
      windows: Windows
    checksum:
      type: http
      url: https://gh-proxy.org/github.com/grafana/mcp-grafana/releases/download/{{.Version}}/mcp-grafana_{{trimV .Version}}_checksums.txt
      asset: mcp-grafana_{{trimV .Version}}_checksums.txt
      algorithm: sha256
    overrides:
      - goos: windows
        type: http
        url: https://gh-proxy.org/github.com/grafana/mcp-grafana/releases/download/{{.Version}}/mcp-grafana_{{.OS}}_{{.Arch}}.{{.Format}}
        format: zip
